/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.editando;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * 
 */

public class edip extends javax.swing.JFrame {
    
    
     File file;
    //Workbook workbook;

    /**
     * 
     */
    public edip() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        painelTop = new javax.swing.JPanel();
        btn_cadas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtdesc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_masculino = new javax.swing.JCheckBox();
        txt_feminino = new javax.swing.JCheckBox();
        txtqtd = new javax.swing.JTextField();
        btn_atualizar = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        canvas1 = new java.awt.Canvas();
        label1 = new java.awt.Label();
        painelbot = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTprodutos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_cadas.setText("Cadastrar");
        btn_cadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadasActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome Completo");

        txtdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescActionPerformed(evt);
            }
        });

        jLabel2.setText("Matricula");

        txt_masculino.setText("Masculino");
        txt_masculino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txt_masculinoItemStateChanged(evt);
            }
        });
        txt_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_masculinoActionPerformed(evt);
            }
        });

        txt_feminino.setText("Feminino");
        txt_feminino.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txt_femininoItemStateChanged(evt);
            }
        });
        txt_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_femininoActionPerformed(evt);
            }
        });

        txtqtd.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtqtdAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtqtd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtqtdMouseClicked(evt);
            }
        });
        txtqtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtdActionPerformed(evt);
            }
        });
        txtqtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtqtdKeyTyped(evt);
            }
        });

        btn_atualizar.setText("Alterar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        btn_del.setText("Apagar");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        label1.setFont(new java.awt.Font("Dulkanyca", 1, 12)); // NOI18N
        label1.setText("TELA DE CADASTRO");

        javax.swing.GroupLayout painelTopLayout = new javax.swing.GroupLayout(painelTop);
        painelTop.setLayout(painelTopLayout);
        painelTopLayout.setHorizontalGroup(
            painelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTopLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(painelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTopLayout.createSequentialGroup()
                        .addComponent(btn_cadas)
                        .addGap(116, 116, 116)
                        .addComponent(btn_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelTopLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(34, 34, 34)
                        .addComponent(txtqtd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(painelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTopLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(painelTopLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_masculino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(30, 30, 30)
                        .addComponent(txt_feminino)
                        .addGap(246, 246, 246))))
            .addGroup(painelTopLayout.createSequentialGroup()
                .addGroup(painelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTopLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelTopLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTopLayout.setVerticalGroup(
            painelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTopLayout.createSequentialGroup()
                .addGroup(painelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelTopLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelTopLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49)
                .addGroup(painelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(painelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtqtd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_masculino)
                    .addComponent(txt_feminino))
                .addGap(19, 19, 19)
                .addGroup(painelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Matricula", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTprodutos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTprodutosComponentAdded(evt);
            }
        });
        jTprodutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTprodutosMouseClicked(evt);
            }
        });
        jTprodutos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTprodutosKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTprodutos);

        javax.swing.GroupLayout painelbotLayout = new javax.swing.GroupLayout(painelbot);
        painelbot.setLayout(painelbotLayout);
        painelbotLayout.setHorizontalGroup(
            painelbotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelbotLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelbotLayout.setVerticalGroup(
            painelbotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelbotLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );

        jLabel3.setText("TODOS OS CAMPOS SÃO OBRIGATÓRIOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(painelTop, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(painelbot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelbot, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        // TODO add your handling code here:
          String sexo = null;
        if (txt_masculino.isSelected()){
            sexo= "Masculino";
        }else if (txt_feminino.isSelected()){
            sexo= "Feminino";}
        
        
        if (jTprodutos.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Selecione uma linha" ,"ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);}
        
        
        
        else {if (txtqtd.getText().isEmpty()|| txtdesc.getText().isEmpty()  || !txt_masculino.isSelected() && !txt_feminino.isSelected()  ){ 
            JOptionPane.showMessageDialog(null, "Faltou preencher um campo" ,"ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        
        }else{ if (jTprodutos.getSelectedRow() != -1){
            
        
            jTprodutos.setValueAt(txtdesc.getText(), jTprodutos.getSelectedRow(), 0);
            jTprodutos.setValueAt(txtqtd.getText(), jTprodutos.getSelectedRow(), 1);
         
            jTprodutos.setValueAt( sexo , jTprodutos.getSelectedRow(), 2);
            JOptionPane.showMessageDialog(null, "Cadastro alterado com sucesso" ,"PARABÉNS",JOptionPane.INFORMATION_MESSAGE);
        
        
            } 
        
        
            
        
        
        
            
        
        } } 
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void txt_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_femininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_femininoActionPerformed

    private void txt_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_masculinoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txt_masculinoActionPerformed

    private void btn_cadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadasActionPerformed
        // TODO add your handling code here:
        // ao apertar no cadastro
        
        
        DefaultTableModel dtmProdutos= (DefaultTableModel)jTprodutos.getModel();
        //da onde os dados vem
        String sexo = null;
        int id= jTprodutos.getRowCount();
        if (txt_masculino.isSelected()){
            sexo= "Masculino";
        }else if (txt_feminino.isSelected()){
            sexo= "Feminino";}
        if (txtqtd.getText().isEmpty()|| txtdesc.getText().isEmpty()  || !txt_masculino.isSelected() && !txt_feminino.isSelected()){ 
            JOptionPane.showMessageDialog(null, "Todos os dados são obrigatorios" ,"ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        
        //} else {
        //}
        //if (!txt_masculino.isSelected() && !txt_feminino.isSelected() ){
          //  JOptionPane.showMessageDialog(null, "Todos os dados são obrigatorios" ,"ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        
        }else{
             Object [] dados = {txtdesc.getText(),txtqtd.getText(),sexo};
             dtmProdutos.addRow(dados);
             txtqtd.setText("");
             txtdesc.setText("");
             txt_masculino.setSelected(false);
             txt_feminino.setSelected(false);
             JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso" ,"PARABÉNS",JOptionPane.INFORMATION_MESSAGE);
        }
        
      
       
	 
        
        
        
        
        
    }//GEN-LAST:event_btn_cadasActionPerformed

    private void txtqtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtdActionPerformed
        // TODO add your handling code here:
        //public void ValidaNumero(txtqtd Numero) { 
	

    }//GEN-LAST:event_txtqtdActionPerformed

    private void txtqtdAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtqtdAncestorAdded
        // TODO add your handling code here:
       
	 
    }//GEN-LAST:event_txtqtdAncestorAdded

    private void txtqtdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtdKeyTyped
        // TODO add your handling code here:
        
                // validar se é numero
        long valor; 
	if (txtqtd.getText().length() != 0){ 
                
		try { 
			valor = Long.parseLong(txtqtd.getText()); 
		}catch(NumberFormatException ex){ 
                        txtqtd.setText("");
			JOptionPane.showMessageDialog(null, "Esse Campo só aceita números" ,"Informação",JOptionPane.INFORMATION_MESSAGE); 
			
                        txtqtd.setText("");
                        txtqtd.grabFocus(); 
                        txtqtd.setText("");
                        
                       
                        
		}   }
	 
    }//GEN-LAST:event_txtqtdKeyTyped

    private void txtqtdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtqtdMouseClicked
        // TODO add your handling code here:
        txtqtd.setText("");
    }//GEN-LAST:event_txtqtdMouseClicked

    private void txt_masculinoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txt_masculinoItemStateChanged
        // TODO add your handling code here:
        // alterando o checkbox
        if (txt_masculino.isSelected()){
            txt_feminino.setSelected(false);
        }
    }//GEN-LAST:event_txt_masculinoItemStateChanged

    private void txt_femininoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txt_femininoItemStateChanged
        // TODO add your handling code here:
        // alterando o checkbox
        if (txt_feminino.isSelected()){
            txt_masculino.setSelected(false);
        }
    }//GEN-LAST:event_txt_femininoItemStateChanged

    private void txtdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO o codigo do botao excluir ( se aparecer -1 quer dizer que nda(nenhum indice) foi selecionado)
       // System.out.println("linha selecionada"+ jTprodutos.getSelectedRow());
       
       if(jTprodutos.getSelectedRow() != -1 ){
       DefaultTableModel dtmProdutos= (DefaultTableModel)jTprodutos.getModel();
        dtmProdutos.removeRow(jTprodutos.getSelectedRow());
       JOptionPane.showMessageDialog(null, "Cadastro excluido com sucesso" ,"ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
       
       
       
       }else{
       
           JOptionPane.showMessageDialog(null,"Selecione um cadastro para EXCLUIR");
       
       
       }       
    }//GEN-LAST:event_btn_delActionPerformed

    private void jTprodutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTprodutosMouseClicked
        // TODO add your handling code here:
        // ao click na table com o mouse
        //o valor é  linha, coluna ( começando a partir de 0)
            if (jTprodutos.getSelectedRow() != -1){
        
            txtdesc.setText(jTprodutos.getValueAt(jTprodutos.getSelectedRow(), 0).toString());
            txtqtd.setText(jTprodutos.getValueAt(jTprodutos.getSelectedRow(), 1).toString());
            
        
        
        
        }
        
        
    }//GEN-LAST:event_jTprodutosMouseClicked

    private void jTprodutosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTprodutosKeyReleased
        // TODO add your handling code here:
        //se nao tiver selecionado nada
            if (jTprodutos.getSelectedRow() != -1){
        
            txtdesc.setText(jTprodutos.getValueAt(jTprodutos.getSelectedRow(), 1).toString());
            txtqtd.setText(jTprodutos.getValueAt(jTprodutos.getSelectedRow(), 2).toString());
            
        
        
        
        }
    }//GEN-LAST:event_jTprodutosKeyReleased

    private void jTprodutosComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTprodutosComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTprodutosComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_cadas;
    private javax.swing.JButton btn_del;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTprodutos;
    private java.awt.Label label1;
    private javax.swing.JPanel painelTop;
    private javax.swing.JPanel painelbot;
    private javax.swing.JCheckBox txt_feminino;
    private javax.swing.JCheckBox txt_masculino;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtqtd;
    // End of variables declaration//GEN-END:variables
}
